In [33]:
import pandas as pd

In [22]:
df = pd.read_csv('terrorismData.csv')
df = df[df['State']=='Jammu and Kashmir']
city = df['City'].value_counts()
print(city.index[0],city.values[0],end=' ')
group = df[df['City']==city.index[0]]
most_group = group['Group'].value_counts()
print(most_group.index[1])

Srinagar 657 Muslim Separatists

In [25]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [40]:
df = pd.read_csv('terrorismData.csv')
country = df['Country'].value_counts()
print(country.index[0],country[0],end=' ')
y = df[df['Country']==country.index[0]]
year = y['Year'].value_counts()
print(year.index[0])

Iraq 24636 2014

In [54]:
df = pd.read_csv('terrorismData.csv')
killed = df[df['Killed']==df['Killed'].max()]
print(int(killed['Killed'].iloc[0]),end=' ')
print(killed['Country'].iloc[0],end=' ')
print(killed['Group'].iloc[0])

1570 Iraq Islamic State of Iraq and the Levant (ISIL)

In [74]:
df = pd.read_csv('terrorismData.csv')
df = df[df['Country']=='India']
df = df[((df['Year']==2014) & (df['Month']== 5) & (df['Day']>=26)) | (df['Year']==2014) & (df['Month'] > 5) | (df['Year'] >2014)]
print(df['Year'].count(),end=' ')
group = df['Group'].value_counts()

print(group.index[1])

3336 Maoists

In [90]:
df = pd.read_csv('terrorismData.csv')
df.head()
city1 = df[(df['State']=="Jharkhand")|(df['State']=="Odisha" )|(df['State']=="Andhra Pradesh")|(df['State']=='Chhattisgarh')]    
city2 = df[df['State']=='Jammu and Kashmir']
casuality1 = (city1['Killed'] +city1['Wounded']).sum()
casuality2 = (city2['Killed'] +city2['Wounded']).sum()
year1 = set()
for i in df['Year']:
    year1.add(i)

length = len(year1)
print(int(casuality1/length),int(casuality2/length))

115 261

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
132468,2014,5,26,India,Andhra Pradesh,South Asia,Bandlapalli,14.714739,77.810281,Bombing/Explosion,0.0,0.0,Party Supporter,05/26/2014: An explosive device was discovered...,Unknown,Private Citizens & Property,Explosives
132496,2014,5,26,India,West Bengal,South Asia,Sandeshkhali,22.356709,88.881991,Armed Assault,0.0,12.0,Party Workers,05/26/2014: Assailants opened fire on Bharatiy...,Unknown,Violent Political Party,Firearms
132502,2014,5,26,India,West Bengal,South Asia,Sandeshkhali,22.363882,88.878679,Armed Assault,0.0,11.0,Members,05/26/2014: Assailants opened fire and threw e...,Unknown,Violent Political Party,Explosives
132526,2014,5,27,India,Jammu and Kashmir,South Asia,Khour,32.601778,74.809414,Bombing/Explosion,0.0,0.0,Unknown,05/27/2014: An explosive device was discovered...,Unknown,Unknown,Explosives
132555,2014,5,27,India,Odisha,South Asia,Bikrampur,22.338542,86.178146,Assassination,1.0,0.0,Journalist: Tarun Kumar Acharya,05/27/2014: Assailants stabbed and killed Taru...,Unknown,Journalists & Media,Melee